import { MigrationInterface, QueryRunner } from "typeorm";

export class InitVehiculosYUsado1720370000000 implements MigrationInterface {
  name = 'InitVehiculosYUsado1720370000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    // === Tabla VehiculoUsado (nombre exacto de tu entidad) ===
    await queryRunner.query(`
      CREATE TABLE "VehiculoUsado" (
        "Id_Vehiculo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "Dominio" VARCHAR(50) NOT NULL,
        "Kilometros" VARCHAR NOT NULL,
        "prov_radic" VARCHAR(65),
        "loc_radic" VARCHAR(65),
        "Observaciones" VARCHAR(255) NOT NULL,
        "año" INTEGER NOT NULL
      );
    `);

    // === Tabla Vehiculos (nombre exacto de tu entidad) ===
    await queryRunner.query(`
      CREATE TABLE "Vehiculos" (
        "Id_Vehiculo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "Marca" VARCHAR(100) NOT NULL,
        "Modelo" VARCHAR(100) NOT NULL,
        "Version" VARCHAR(100) NOT NULL,
        "Transmision" VARCHAR(100) NOT NULL,
        "Combustible" VARCHAR(100) NOT NULL,
        "Color" VARCHAR(100) NOT NULL,

        "marca_motor" VARCHAR(65),
        "numero_motor" VARCHAR(65),
        "marca_chasis" VARCHAR(65),
        "numero_chasis" VARCHAR(65),
        "moneda" VARCHAR(65),

        "Valor_Venta" INTEGER DEFAULT 0,
        "Valor_Costo" INTEGER DEFAULT 0,

        "Peritada" VARCHAR NOT NULL DEFAULT 'NO',
        "UBICACION" VARCHAR NOT NULL DEFAULT 'SALON',

        -- Columna de la relación OneToOne con Usado (por JoinColumn)
        "TipoVehiculo" INTEGER,

        CONSTRAINT "FK_Vehiculos_TipoVehiculo_Usado"
          FOREIGN KEY ("TipoVehiculo")
          REFERENCES "VehiculoUsado"("Id_Vehiculo")
          ON DELETE SET NULL
          ON UPDATE CASCADE
      );
    `);

    await queryRunner.query(`CREATE INDEX "IDX_Vehiculos_Marca" ON "Vehiculos" ("Marca");`);
    await queryRunner.query(`CREATE UNIQUE INDEX "UQ_VehiculoUsado_Dominio" ON "VehiculoUsado" ("Dominio");`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "UQ_VehiculoUsado_Dominio";`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_Vehiculos_Marca";`);
    await queryRunner.query(`ALTER TABLE "Vehiculos" DROP CONSTRAINT IF EXISTS "FK_Vehiculos_TipoVehiculo_Usado";`);
    await queryRunner.query(`DROP TABLE IF EXISTS "Vehiculos";`);
    await queryRunner.query(`DROP TABLE IF EXISTS "VehiculoUsado";`);
  }
}
